// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  GCommand = 4,
  MCommand = 5,
  ControlKeyword = 6,
  ControlOperator = 7,
  Function = 8,
  Variables = 9,
  Axis = 10,
  Position = 11,
  FeedSpeed = 12,
  ON = 13,
  Brackets = 14
